version: "3"

services:
  db:
    image: mariadb:10.3
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
  nginx:
    image: nginx:latest
    ports:
      - ${API_PORT}:80
    links:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./lumen
    tty: true
    volumes:
      - ${APP_CODE_PATH_HOST}:/app
    depends_on:
      - db

